### ISSUE TITLE
Red tests

### ISSUE THREAD

**Issue by FoggyFinder** [JohanLarsson/Gu.Wpf.UiAutomation#43]
There are a few of red tests on my machine:

![_ui](https://user-images.githubusercontent.com/16510738/33233992-d935dd80-d227-11e7-98cd-fefca83e6009.jpg)

some of them is obvious, but some is totally unexpected, does it correct behaviour?

**Comment by JohanLarsson** [comment]
What OS are you using? The tests are somewhat fragile but I've been struggling to get them to pass on win 7, win 10 & appveyor.

**Comment by JohanLarsson** [comment]
If you are adding a feature or fixing something you can go ahead and ignore if some unrelated test fails and we can try to solve it together.

**Comment by FoggyFinder** [comment]
Win7

Some of them fails because my machine has other localization, so, for example, [here](https://github.com/JohanLarsson/Gu.Wpf.UiAutomation/blob/master/Gu.Wpf.UiAutomation.UITests/Elements/CheckBoxTests.cs#L65):

```csharp
 var exception = Assert.Throws<UiAutomationException>(() => checkBox.IsChecked = null);
 Assert.AreEqual(
    "Setting AutomationId:SimpleCheckBox, Name:Test Checkbox, ControlType:check box, FrameworkId:WPF .IsChecked to null failed.",
    exception.Message);
```

according to

```csharp
return $"AutomationId:{this.Properties.AutomationId.ValueOrDefault("MISSING")}, Name:{this.Properties.Name.ValueOrDefault("MISSING")}, ControlType:{this.Properties.LocalizedControlType.ValueOrDefault("MISSING")}, FrameworkId:{this.Properties.FrameworkId.ValueOrDefault("MISSING")}";```
```


returns `флажок` instead of `check box`

**Comment by FoggyFinder** [comment]
Some thoughts:
15/29 'pass for me after small changed in #45 

Regarding remaining 14 red tests:

---

2/14

* NotepadFindFirst
* FocusChangedWithPaintTest

the reason in simple switch

```csharp
 switch (CultureInfo.InstalledUICulture.TwoLetterISOLanguageName)
 {
    case "de": return ...
    default: return ...
}
```

so, someone who want to see green test have to add his locale to the list. 

---

3/14

* PressScanCode
* TypeKey
* TypeKeyWhilePressingShift

the same reason like group above except that there is no switch. 

---

1/14

* CalculatorTest

There is no explicit localization problem but I guess the reason the same.

---

7/ 14

* Size
* SlideThumbTest
* WhenEqualExplicitPath
* WhenEqualRelativePath
* WhenEqualResource
* WhenEqualRelativePath
* WhenNotEqual

Someone may have settings for changing text size by default for example by 125%. So Size will be different. If there any properties for getting the coefficient then the test could be green. But anyway I think this is a rare case so not very important. 

---

1/14

* Window

I was mentioning about it in gitter. Perhaps make sense create separate issues for this.

**Comment by JohanLarsson** [comment]
Nice writeup, thanks for taking the time to do this!

**Comment by JohanLarsson** [comment]
Refactored things, maybe fixed some of these by accident, maybe broke things.

**Comment by FoggyFinder** [comment]
Can't run test now:

> [03.01.2018 19:03:20 Warning]    в Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
>    в Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
>    в Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
>    в Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
>    в Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
>    в Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
>    в NUnit.VisualStudio.TestAdapter.NavigationDataProvider.CacheNewTypes(String assemblyPath, IDictionary`2 types)
>    в NUnit.VisualStudio.TestAdapter.NavigationDataProvider.GetNavigationData(String className, String methodName)
>    в NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestCaseFromXmlNode(XmlNode testNode)
>    в NUnit.VisualStudio.TestAdapter.TestConverter.ConvertTestCase(XmlNode testNode)
>    в NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter)

**Comment by JohanLarsson** [comment]
What is this hipster stack? Are you using Linux?

**Comment by FoggyFinder** [comment]
lol, no
is was happening due to 

https://github.com/nunit/nunit3-vs-adapter/issues/296

so works now.

I'm going to close this issue and open new if see something specific cause there a some new red test
