### ISSUE TITLE
DataGrid.RowCount: Exception when ItemSource is empty collection

### ISSUE THREAD

**Issue by FoggyFinder** [JohanLarsson/Gu.Wpf.UiAutomation#46]
DataGrid.RowCount throws `InvalidOperationException` [here](https://github.com/JohanLarsson/Gu.Wpf.UiAutomation/blob/master/Gu.Wpf.UiAutomation/UIA3/Patterns/GridPattern.cs#L24-L33) when `ItemSource` is empty collection.

```csharp
public override T GetItem<T>(int row, int column, Func<BasicAutomationElementBase, T> wrap)
{
    var nativeItem = Com.Call(() => this.NativePattern.GetItem(row, column));
    if (nativeItem == null)
    {
        throw new InvalidOperationException("Did not find item.");
    }

    return wrap(new UIA3BasicAutomationElement((UIA3Automation)this.BasicAutomationElement.Automation, nativeItem));
}
```
If set `CanUserAddRows="False"` it works fine.

**Comment by JohanLarsson** [comment]
We should probably spexialcase it, not sure what is best, maybe just write the simplest we can come up with and throw some tests at it?
