### ISSUE TITLE
Find all UI element by frameworkid

### ISSUE THREAD

**Issue by davishoang96** [JohanLarsson/Gu.Wpf.UiAutomation#49]
Hi, I'm developing a UI spy program. I did try both Teststack and FlaUI frameworks to get all element of an AUT (Application Under Test). 

This is how I get those UI element in FlaUI by frameworkid and use foreach to print them to the console.

```
var ItemList = AUTWindow.FindAllDescendants(new PropertyCondition(automation.PropertyLibrary.Element.FrameworkId, "WPF"));
```

I did use your framework Gu.Wpf:

```
var element = MainWindow.FindAllDescendants(Condition.);
```
Although there isn't any option to check by framework. So how can I write it in Gu.WPF.  

Thanks

**Comment by JohanLarsson** [comment]
Hi,
Something like this should work:
```cs
using (var app = Application.AttachOrLaunch(ExeFileName, "ButtonWindow"))
{
    var window = app.MainWindow;
    var wrapped = window.FindAll(TreeScope.Descendants, new PropertyCondition(AutomationElement.FrameworkIdProperty, "WPF"));
    var raw = window.AutomationElement.FindAll(TreeScope.Descendants, new PropertyCondition(AutomationElement.FrameworkIdProperty, "WPF"));
}
```

For an UI spy program you probably want a tree. I added a property to `UiElement`

```cs
public IReadOnlyList<UiElement> Children => this.FindAllChildren();
````

Releasing an updates package later tonight.

Do you have a link to your project?

**Comment by JohanLarsson** [comment]
Also this library is as the name suggests only meant for WPF apps, if something works with WinForms it is by accident and may break in the future :)

**Comment by davishoang96** [comment]
Thank you for your guidance. I used your code and it does print all what I need to the console. 

```
var element = MainWindow.FindAll(TreeScope.Descendants, new PropertyCondition(AutomationElement.FrameworkIdProperty, "WPF"));
using (StreamWriter writetext = new StreamWriter("write.txt"))
{
         int i = 0;
         foreach (Gu.Wpf.UiAutomation.UiElement btn in element)
         {
                writetext.WriteLine(i + " - " + btn);
                i++;
         }
}
```

I'm using for framework to spy some UI elements on devExpress and trying to playback the comboboxEdit on devexpress. 

Thank you, we love your works.
